# [START runtime]
runtime: python37
entrypoint: gunicorn -b :$PORT PTCG2win.wsgi
instance_class: F4
handlers:

- url: /static
  static_dir: static/
- url: /.*
  script: auto

beta_settings:
    cloud_sql_instances: ptcg2win:asia-northeast1:ptcg2win
automatic_scaling:
    min_idle_instances: automatic   # idle状態にあるインスタンスの最小値
    max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
    min_pending_latency: 3000ms  # リクエストを処理するまでに許される待ち時間の最小
    max_pending_latency: automatic
# [END runtime]
